// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/im.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Пакет, летящий от клиента на сервер при отправке сообщения
// Payload sent from the client to the server upon message transmission
type MessageFromClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TextContent   string                 `protobuf:"bytes,2,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"` // Жесткий лимит до 1000 символов / Hard limit up to 1000 characters
	ClientUuid    string                 `protobuf:"bytes,3,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`    // Для дедупликации сессий / For session deduplication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageFromClient) Reset() {
	*x = MessageFromClient{}
	mi := &file_api_v1_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFromClient) ProtoMessage() {}

func (x *MessageFromClient) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFromClient.ProtoReflect.Descriptor instead.
func (*MessageFromClient) Descriptor() ([]byte, []int) {
	return file_api_v1_im_proto_rawDescGZIP(), []int{0}
}

func (x *MessageFromClient) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageFromClient) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *MessageFromClient) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

// Пакет, летящий от сервера к клиенту в реальном времени
// Payload broadcasted from the server to the client in real time
type MessageFromServer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RoomId         string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TextContent    string                 `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeliveryStatus string                 `protobuf:"bytes,6,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"` // DELIVERED, READ
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageFromServer) Reset() {
	*x = MessageFromServer{}
	mi := &file_api_v1_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFromServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFromServer) ProtoMessage() {}

func (x *MessageFromServer) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFromServer.ProtoReflect.Descriptor instead.
func (*MessageFromServer) Descriptor() ([]byte, []int) {
	return file_api_v1_im_proto_rawDescGZIP(), []int{1}
}

func (x *MessageFromServer) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageFromServer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageFromServer) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageFromServer) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *MessageFromServer) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MessageFromServer) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

// Запрос истории сообщений кусками по 30 штук
// Request for chat history in chunks of exactly 30 messages
type HistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CursorMessageId string                 `protobuf:"bytes,2,opt,name=cursor_message_id,json=cursorMessageId,proto3" json:"cursor_message_id,omitempty"` // ID крайнего сообщения. Если пуст - берем топ-30 свежих / Last known message ID. If empty - fetches top-30 fresh
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                             // Всегда равен 30 по ТЗ / Always hardcoded to 30 per SRS requirements
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_api_v1_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_im_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *HistoryRequest) GetCursorMessageId() string {
	if x != nil {
		return x.CursorMessageId
	}
	return ""
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Ответ сервера со списком сообщений истории
// Server response containing the historical message slice
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageFromServer   `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`                               // Массив из макс. 30 сообщений / Array of max 30 messages
	NextCursorId  string                 `protobuf:"bytes,2,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"` // Новый курсор для следующей подгрузки / New cursor ID for the next lazy-load iteration
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                 // Флаг: есть ли сообщения дальше в истории / Flag: indicates if deeper history exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_api_v1_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_im_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryResponse) GetMessages() []*MessageFromServer {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *HistoryResponse) GetNextCursorId() string {
	if x != nil {
		return x.NextCursorId
	}
	return ""
}

func (x *HistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Запрос статуса присутствия пользователя
// Request for user presence state tracking
type PresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceRequest) Reset() {
	*x = PresenceRequest{}
	mi := &file_api_v1_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRequest) ProtoMessage() {}

func (x *PresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRequest.ProtoReflect.Descriptor instead.
func (*PresenceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_im_proto_rawDescGZIP(), []int{4}
}

func (x *PresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ сервера о статусе активности за последнюю минуту
// Server response regarding user activity state within the last minute
type PresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsOnline      bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`        // true если был пинг за последнюю минуту / true if a heartbeat ping occurred within 60 seconds
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"` // Точный час крайнего визита, если offline / Exact timestamp of the last action if offline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceResponse) Reset() {
	*x = PresenceResponse{}
	mi := &file_api_v1_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceResponse) ProtoMessage() {}

func (x *PresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceResponse.ProtoReflect.Descriptor instead.
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_im_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceResponse) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *PresenceResponse) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

var File_api_v1_im_proto protoreflect.FileDescriptor

const file_api_v1_im_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/v1/im.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\x11MessageFromClient\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\ftext_content\x18\x02 \x01(\tR\vtextContent\x12\x1f\n" +
	"\vclient_uuid\x18\x03 \x01(\tR\n" +
	"clientUuid\"\xee\x01\n" +
	"\x11MessageFromServer\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12!\n" +
	"\ftext_content\x18\x04 \x01(\tR\vtextContent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fdelivery_status\x18\x06 \x01(\tR\x0edeliveryStatus\"k\n" +
	"\x0eHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12*\n" +
	"\x11cursor_message_id\x18\x02 \x01(\tR\x0fcursorMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x89\x01\n" +
	"\x0fHistoryResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.api.v1.MessageFromServerR\bmessages\x12$\n" +
	"\x0enext_cursor_id\x18\x02 \x01(\tR\fnextCursorId\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"*\n" +
	"\x0fPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x86\x01\n" +
	"\x10PresenceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\x12<\n" +
	"\flast_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt2\xf1\x01\n" +
	"\x16InstantMessagingEngine\x12N\n" +
	"\x12RealTimeChatStream\x12\x19.api.v1.MessageFromClient\x1a\x19.api.v1.MessageFromServer(\x010\x01\x12A\n" +
	"\x0eGetChatHistory\x12\x16.api.v1.HistoryRequest\x1a\x17.api.v1.HistoryResponse\x12D\n" +
	"\x0fGetUserPresence\x12\x17.api.v1.PresenceRequest\x1a\x18.api.v1.PresenceResponseB<Z:preparing-for-the-interview/system-instant-messaging/pb;pbb\x06proto3"

var (
	file_api_v1_im_proto_rawDescOnce sync.Once
	file_api_v1_im_proto_rawDescData []byte
)

func file_api_v1_im_proto_rawDescGZIP() []byte {
	file_api_v1_im_proto_rawDescOnce.Do(func() {
		file_api_v1_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_im_proto_rawDesc), len(file_api_v1_im_proto_rawDesc)))
	})
	return file_api_v1_im_proto_rawDescData
}

var file_api_v1_im_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_im_proto_goTypes = []any{
	(*MessageFromClient)(nil),     // 0: api.v1.MessageFromClient
	(*MessageFromServer)(nil),     // 1: api.v1.MessageFromServer
	(*HistoryRequest)(nil),        // 2: api.v1.HistoryRequest
	(*HistoryResponse)(nil),       // 3: api.v1.HistoryResponse
	(*PresenceRequest)(nil),       // 4: api.v1.PresenceRequest
	(*PresenceResponse)(nil),      // 5: api.v1.PresenceResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_v1_im_proto_depIdxs = []int32{
	6, // 0: api.v1.MessageFromServer.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: api.v1.HistoryResponse.messages:type_name -> api.v1.MessageFromServer
	6, // 2: api.v1.PresenceResponse.last_seen_at:type_name -> google.protobuf.Timestamp
	0, // 3: api.v1.InstantMessagingEngine.RealTimeChatStream:input_type -> api.v1.MessageFromClient
	2, // 4: api.v1.InstantMessagingEngine.GetChatHistory:input_type -> api.v1.HistoryRequest
	4, // 5: api.v1.InstantMessagingEngine.GetUserPresence:input_type -> api.v1.PresenceRequest
	1, // 6: api.v1.InstantMessagingEngine.RealTimeChatStream:output_type -> api.v1.MessageFromServer
	3, // 7: api.v1.InstantMessagingEngine.GetChatHistory:output_type -> api.v1.HistoryResponse
	5, // 8: api.v1.InstantMessagingEngine.GetUserPresence:output_type -> api.v1.PresenceResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_im_proto_init() }
func file_api_v1_im_proto_init() {
	if File_api_v1_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_im_proto_rawDesc), len(file_api_v1_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_im_proto_goTypes,
		DependencyIndexes: file_api_v1_im_proto_depIdxs,
		MessageInfos:      file_api_v1_im_proto_msgTypes,
	}.Build()
	File_api_v1_im_proto = out.File
	file_api_v1_im_proto_goTypes = nil
	file_api_v1_im_proto_depIdxs = nil
}
