// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/v1/im.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstantMessagingEngine_RealTimeChatStream_FullMethodName = "/api.v1.InstantMessagingEngine/RealTimeChatStream"
	InstantMessagingEngine_GetChatHistory_FullMethodName     = "/api.v1.InstantMessagingEngine/GetChatHistory"
	InstantMessagingEngine_GetUserPresence_FullMethodName    = "/api.v1.InstantMessagingEngine/GetUserPresence"
)

// InstantMessagingEngineClient is the client API for InstantMessagingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InstantMessagingEngine управляет real-time чатами, историей и статусами присутствия
// InstantMessagingEngine orchestrates real-time chats, message history, and user presence states
type InstantMessagingEngineClient interface {
	// 1. Bi-directional Streaming: Двусторонний канал для обмена сообщениями в реальном времени
	// 1. Bi-directional Streaming: Full-duplex channel for real-time messaging
	RealTimeChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageFromClient, MessageFromServer], error)
	// 2. Unary RPC: Запрос истории сообщений кусками по 30 штук (Cursor Пагинация)
	// 2. Unary RPC: Fetching message history chunks of exactly 30 items (Cursor Pagination)
	GetChatHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	// 3. Unary RPC: Запрос статуса активности конкретного пользователя (За последнюю минуту)
	// 3. Unary RPC: Querying the presence status of a specific user (within the last 1-minute window)
	GetUserPresence(ctx context.Context, in *PresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error)
}

type instantMessagingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewInstantMessagingEngineClient(cc grpc.ClientConnInterface) InstantMessagingEngineClient {
	return &instantMessagingEngineClient{cc}
}

func (c *instantMessagingEngineClient) RealTimeChatStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageFromClient, MessageFromServer], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InstantMessagingEngine_ServiceDesc.Streams[0], InstantMessagingEngine_RealTimeChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessageFromClient, MessageFromServer]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstantMessagingEngine_RealTimeChatStreamClient = grpc.BidiStreamingClient[MessageFromClient, MessageFromServer]

func (c *instantMessagingEngineClient) GetChatHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, InstantMessagingEngine_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instantMessagingEngineClient) GetUserPresence(ctx context.Context, in *PresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceResponse)
	err := c.cc.Invoke(ctx, InstantMessagingEngine_GetUserPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstantMessagingEngineServer is the server API for InstantMessagingEngine service.
// All implementations must embed UnimplementedInstantMessagingEngineServer
// for forward compatibility.
//
// InstantMessagingEngine управляет real-time чатами, историей и статусами присутствия
// InstantMessagingEngine orchestrates real-time chats, message history, and user presence states
type InstantMessagingEngineServer interface {
	// 1. Bi-directional Streaming: Двусторонний канал для обмена сообщениями в реальном времени
	// 1. Bi-directional Streaming: Full-duplex channel for real-time messaging
	RealTimeChatStream(grpc.BidiStreamingServer[MessageFromClient, MessageFromServer]) error
	// 2. Unary RPC: Запрос истории сообщений кусками по 30 штук (Cursor Пагинация)
	// 2. Unary RPC: Fetching message history chunks of exactly 30 items (Cursor Pagination)
	GetChatHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	// 3. Unary RPC: Запрос статуса активности конкретного пользователя (За последнюю минуту)
	// 3. Unary RPC: Querying the presence status of a specific user (within the last 1-minute window)
	GetUserPresence(context.Context, *PresenceRequest) (*PresenceResponse, error)
	mustEmbedUnimplementedInstantMessagingEngineServer()
}

// UnimplementedInstantMessagingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstantMessagingEngineServer struct{}

func (UnimplementedInstantMessagingEngineServer) RealTimeChatStream(grpc.BidiStreamingServer[MessageFromClient, MessageFromServer]) error {
	return status.Error(codes.Unimplemented, "method RealTimeChatStream not implemented")
}
func (UnimplementedInstantMessagingEngineServer) GetChatHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedInstantMessagingEngineServer) GetUserPresence(context.Context, *PresenceRequest) (*PresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPresence not implemented")
}
func (UnimplementedInstantMessagingEngineServer) mustEmbedUnimplementedInstantMessagingEngineServer() {
}
func (UnimplementedInstantMessagingEngineServer) testEmbeddedByValue() {}

// UnsafeInstantMessagingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstantMessagingEngineServer will
// result in compilation errors.
type UnsafeInstantMessagingEngineServer interface {
	mustEmbedUnimplementedInstantMessagingEngineServer()
}

func RegisterInstantMessagingEngineServer(s grpc.ServiceRegistrar, srv InstantMessagingEngineServer) {
	// If the following call panics, it indicates UnimplementedInstantMessagingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstantMessagingEngine_ServiceDesc, srv)
}

func _InstantMessagingEngine_RealTimeChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InstantMessagingEngineServer).RealTimeChatStream(&grpc.GenericServerStream[MessageFromClient, MessageFromServer]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstantMessagingEngine_RealTimeChatStreamServer = grpc.BidiStreamingServer[MessageFromClient, MessageFromServer]

func _InstantMessagingEngine_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstantMessagingEngineServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstantMessagingEngine_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstantMessagingEngineServer).GetChatHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstantMessagingEngine_GetUserPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstantMessagingEngineServer).GetUserPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstantMessagingEngine_GetUserPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstantMessagingEngineServer).GetUserPresence(ctx, req.(*PresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstantMessagingEngine_ServiceDesc is the grpc.ServiceDesc for InstantMessagingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstantMessagingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.InstantMessagingEngine",
	HandlerType: (*InstantMessagingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatHistory",
			Handler:    _InstantMessagingEngine_GetChatHistory_Handler,
		},
		{
			MethodName: "GetUserPresence",
			Handler:    _InstantMessagingEngine_GetUserPresence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RealTimeChatStream",
			Handler:       _InstantMessagingEngine_RealTimeChatStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/im.proto",
}
