events {
    worker_connections 1024;
}

http {
    # Явно указываем DNS докера. ipv6=off критичен для Windows!
    resolver 127.0.0.11 ipv6=off valid=5s;

    server {
        listen 80;

    location / {
        resolver 127.0.0.11 ipv6=off valid=2s;
        
        # Добавляем tasks. — это заставит Docker отдать список всех IP реплик
        set $backend_name "tasks.go-server"; 
        
        proxy_pass http://$backend_name:8080;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Отключаем кэширование соединений, чтобы каждый раз выбирать новый бэкенд
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }



        location /health {
            return 200 "OK";
        }
    }
}
