events {
    worker_connections 1024;
}

http {
    # Явно указываем DNS докера. ipv6=off критичен для Windows!
    resolver 127.0.0.11 ipv6=off valid=5s;

    server {
        listen 80;

    location / {
        # Попробуйте полное имя: имяСтека_имяСервиса
        set $backend_name "my_stack_go-server"; 
        
        proxy_pass http://$backend_name:8080;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        resolver 127.0.0.11 ipv6=off;
    }


        location /health {
            return 200 "OK";
        }
    }
}
